test_path = r"C:\Users\Isaac's\Desktop\Isaac's Synth Music Source Folder\FL\Tower Projects File\9_Scribed Musicode Midi\\"

#Individualized Musicode Tests
splyce_test_letters = translate("Splyce", "AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz")
splyce_test_letters.write("mid", test_path + "splyce_test_letters.mid")
splyce_test_numbers = translate("Splyce", "0123456789")
splyce_test_numbers.write("mid", test_path + "splyce_test_numbers.mid")
splyce_test_punctuation = translate("Splyce", ''',;' :- .!" ()[]/''')
splyce_test_punctuation.write("mid", test_path + "splyce_test_puncutation.mid")

bp_test_letters = translate("BraillePulse", "AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz")
bp_test_letters.write("mid", test_path + "bp_test_letters.mid")
bp_test_numbers = translate("BraillePulse", "0123456789")
bp_test_numbers.write("mid", test_path + "bp_test_numbers.mid")
bp_test_punct = translate("BraillePulse", ''',;' :- .!" ()[]/''')
bp_test_punct.write("mid", test_path + "bp_test_punct.mid")#TODO reCHECK BraillePulse Punctuation

mm_test_letters = translate("MetaMorse", "AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz")
mm_test_letters.write("mid", test_path + "mm_test_letters.mid")
mm_test_numbers = translate("MetaMorse", "0123456789")
mm_test_numbers.write("mid", test_path + "mm_test_numbers.mid")
mm_test_punct = translate("MetaMorse", ''',;' :- .!" ()[]/''')
mm_test_punct.write("mid", test_path + "mm_test_punct.mid")

am_test_letters = translate("Animuse", "AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz")
am_test_letters.write("mid", test_path + "am_test_letters.mid")
am_test_numbers = translate("Animuse", "0123456789")
am_test_numbers.write("mid", test_path + "am_test_numbers.mid")
am_test_punct = translate("Animuse", ''',;' :- .!" ()[]/''')
am_test_punct.write("mid", test_path + "am_test_punct.mid")

ascii_test_letters = translate("Asciipher", "AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz")
ascii_test_letters.write("mid", test_path + "ascii_test_letters.mid")
ascii_test_numbers = translate("Asciipher", "0123456789")
ascii_test_numbers.write("mid", test_path + "ascii_test_numbers.mid")
ascii_test_punct = translate("Asciipher", ''',;' :- .!" ()[]/''')
ascii_test_punct.write("mid", test_path + "ascii_test_punct.mid")

asciiX_test_letters = translate("Asciipher_X", "AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz")
asciiX_test_letters.write("mid", test_path + "asciiX_test_letters.mid")
asciiX_test_numbers = translate("Asciipher_X", "0123456789")
asciiX_test_numbers.write("mid", test_path + "asciiX_test_numbers.mid")
asciiX_test_punct = translate("Asciipher_X", ''',;' :- .!" ()[]/''')
asciiX_test_punct.write("mid", test_path + "asciiX_test_punct.mid")

asciiY_test_letters = translate("Asciipher_Y", "AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz")
asciiY_test_letters.write("mid", test_path + "asciiY_test_letters.mid")
asciiY_test_numbers = translate("Asciipher_Y", "0123456789")
asciiY_test_numbers.write("mid", test_path + "asciiY_test_numbers.mid")
asciiY_test_punct = translate("Asciipher_Y", ''',;' :- .!" ()[]/''')
asciiY_test_punct.write("mid", test_path + "asciiY_test_punct.mid")

pt_test_letters = translate("POWerTap", "AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz")
pt_test_letters.write("mid", test_path + "pt_test_letters.mid")
pt_test_numbers = translate("POWerTap", "0123456789")
pt_test_numbers.write("mid", test_path + "pt_test_numbers.mid")
pt_test_punct = translate("POWerTap", ''',;' :- .!" ()[]/''')
pt_test_punct.write("mid", test_path + "pt_test_punct.mid")

ptX_test_letters = translate("POWerTap_X", "AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz")
ptX_test_letters.write("mid", test_path + "ptX_test_letters.mid")
ptX_test_numbers = translate("POWerTap_X", "0123456789")
ptX_test_numbers.write("mid", test_path + "ptX_test_numbers.mid")
ptX_test_punct = translate("POWerTap_X", ''',;' :- .!" ()[]/''')
ptX_test_punct.write("mid", test_path + "ptX_test_punct.mid")

ptY_test_letters = translate("POWerTap_Y", "AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz")
ptY_test_letters.write("mid", test_path + "ptY_test_letters.mid")
ptY_test_numbers = translate("POWerTap_Y", "0123456789")
ptY_test_numbers.write("mid", test_path + "ptY_test_numbers.mid")
ptY_test_punct = translate("POWerTap_Y", ''',;' :- .!" ()[]/''')
ptY_test_punct.write("mid", test_path + "ptY_test_punct.mid")

#All Musicodes-All Characters Test
bp_test_all = translate("BraillePulse", "AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz          ?,;\':-.!\"()[]/   0123456789")
bp_test_all.write("mid", test_path + "bp_test_all.mid")
mm_test_all = translate("MetaMorse", "AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz          ?,;\':-.!\"()[]/   0123456789")
mm_test_all.write("mid", test_path + "mm_test_all.mid")
am_test_all = translate("Animuse", "AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz          ?,;\':-.!\"()[]/   0123456789")
am_test_all.write("mid", test_path + "am_test_all.mid")
asciiX_test_all = translate("Asciipher_X", "AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz          ?,;\':-.!\"()[]/   0123456789")
asciiX_test_all.write("mid", test_path + "asciiX_test_all.mid")
asciiY_test_all = translate("Asciipher_Y", "AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz          ?,;\':-.!\"()[]/   0123456789")
asciiY_test_all.write("mid", test_path + "asciiY_test_all.mid")
ptX_test_all = translate("POWerTap_X", "AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz          ?,;\':-.!\"()[]/   0123456789")
ptX_test_all.write("mid", test_path + "ptX_test_all.mid")
ptY_test_all = translate("POWerTap_Y", "AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz          ?,;\':-.!\"()[]/   0123456789")
ptY_test_all.write("mid", test_path + "ptY_test_all.mid")
splyce_test_all = translate("Splyce", "AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz          ?,;\':-.!\"()[]/   0123456789")
splyce_test_all.write("mid", test_path + "splyce_test_all.mid")